INSERT INTO Race(race_id, nom) VALUES (1, 'Nain')
INSERT INTO Race(race_id, nom) VALUES (2, 'Troll')
INSERT INTO Race(race_id, nom) VALUES (3, 'Goblin')
INSERT INTO Race(race_id, nom) VALUES (4, 'Paladin')
INSERT INTO Race(race_id, nom) VALUES (5, 'Sorcier')
INSERT INTO Race(race_id, nom) VALUES (6, 'Shaman')
INSERT INTO Competence(competence_id, nom, valeur) VALUES (1, 'Coup d épée', 1)
INSERT INTO Competence(competence_id, nom, valeur) VALUES (2, 'Tir à l arc', 1)
INSERT INTO Competence(competence_id, nom, valeur) VALUES (3, 'Lancer un sort', 1)